// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDORJaogWQiju5umdYIZ9oiWM7sKFOlY',
    appId: '1:485944454363:web:3d51a86e1be48f641c30fe',
    messagingSenderId: '485944454363',
    projectId: 'mydoctor-16925',
    authDomain: 'mydoctor-16925.firebaseapp.com',
    storageBucket: 'mydoctor-16925.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZK7_dU1vc5gjAx9uKIczK5x85D9k6MT4',
    appId: '1:485944454363:android:a65e150b99cca2da1c30fe',
    messagingSenderId: '485944454363',
    projectId: 'mydoctor-16925',
    storageBucket: 'mydoctor-16925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjhG7aB8cDY4WSx4ZjBNzwdsWSxfEb4do',
    appId: '1:485944454363:ios:3b60e43248da60b71c30fe',
    messagingSenderId: '485944454363',
    projectId: 'mydoctor-16925',
    storageBucket: 'mydoctor-16925.appspot.com',
    iosClientId: '485944454363-2n0c99ck09t7cer7bbiktiq05i9hmrk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjhG7aB8cDY4WSx4ZjBNzwdsWSxfEb4do',
    appId: '1:485944454363:ios:3b60e43248da60b71c30fe',
    messagingSenderId: '485944454363',
    projectId: 'mydoctor-16925',
    storageBucket: 'mydoctor-16925.appspot.com',
    iosClientId: '485944454363-2n0c99ck09t7cer7bbiktiq05i9hmrk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterApp',
  );
}
